
FROM php:5.6-fpm

MAINTAINER ykq <mahmoud@zalt.me>







#####################################
# Opcache:
#####################################

ARG INSTALL_OPCACHE=false
RUN if [ ${INSTALL_OPCACHE} = true ]; then \
    docker-php-ext-install opcache \
;fi

# Copy opcache configration
COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini


#####################################
# ImageMagick:
#####################################
USER root
ARG INSTALL_IMAGEMAGICK=false
ENV INSTALL_IMAGEMAGICK ${INSTALL_IMAGEMAGICK}
RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
    apt-get update -y && \
    apt-get install -y libmagickwand-dev imagemagick && \
    pecl install imagick && \
    docker-php-ext-enable imagick \
;fi



#####################################
# mysql:
#####################################

RUN docker-php-ext-install mysql 
RUN docker-php-ext-install mysqli 
RUN docker-php-ext-install pdo_mysql


#####################################
# Check PHP version:
#####################################

RUN php -v | head -n 1 | grep -q "PHP 5.6."

#
#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------
#

#ADD ./laravel.ini /usr/local/etc/php/conf.d
#ADD ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/

#RUN rm -r /var/lib/apt/lists/*

RUN usermod -u 1000 www-data

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000
